---
title: "9.10.2024 Class Nores"
author: "Koko"
date: "2024-09-10"
output: html_document
---

Will need this for project 1 part 2 

```{r}

library(tidyverse)

outcomes <- tibble(
    id = rep(c("a", "b", "c"), each = 3),
    visit = rep(0:2, 3),
    outcome = rnorm(3 * 3, 3)
)
#have the info, but not easily accessible- extract info 


print(outcomes)

```


```{r}
subjects <- tibble(
    id = c("a", "b", "c"),
    house = c("detached", "rowhouse", "rowhouse")
)

print(subjects)

```

```{r}
library(knitr)
join_funcs <- data.frame(
    func = c(
        "`left_join()`",
        "`right_join()`",
        "`inner_join()`",
        "`full_join()`"
    ),
    does = c(
        "Includes all observations in the left data frame, whether or not there is a match in the right data frame",
        "Includes all observations in the right data frame, whether or not there is a match in the left data frame",
        "Includes only observations that are in both data frames",
        "Includes all observations from both data frames"
    )
)
knitr::kable(join_funcs, col.names = c("Function", "What it includes in merged data frame"))

```
```{r}
outcomes
subjects
```

```{r}
left_join(x = outcomes, y = subjects, by = "id")
full_join(x= outcomes, y=subjects, by= "id")

```


GGplot 2 `
```{r}
library("tidyverse")
library("here")
maacs <- read_csv(here("data", "bmi_pm25_no2_sim.csv"),
    col_types = "nnci"
)

```

```{r}
g <- ggplot(maacs, aes(
    x = logpm25,
    y = NocturnalSympt
))
summary(g)
```


```{r}
g <- maacs %>%
    ggplot(aes(logpm25, NocturnalSympt))
print(g)
```

```{r}
g <- maacs %>%
    ggplot(aes(logpm25, NocturnalSympt))
g + geom_point()
```

#add smooth line

```{r}
g +
    geom_point() +
    geom_smooth()
```

#add linear relationship 

```{r}

g +
    geom_point() +
    geom_smooth(method = "lm")
```



#data for 340 penguins

```{r}
install.packages("palmerpenguins")
library(palmerpenguins)

glimpse(penguins)
```

```{r}
penguins %>%
  ggplot(mapping= aes(x= flipper_length_mm, y= bill_length_mm,
  color= species)) + 
  geom_point()+ 
  geom_smooth(method= "lm")
```
maacs


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
