---
title: "Project 1"
author: "Koko"
date: "2024-09-08"
output: html_document
---

```{r}
#Install packages 
library("tidyverse")

if (!require("tidytuesdayR", quietly = TRUE)) {
    install.packages("tidytuesdayR")
}

## Install the remotes package if you don't have it
if (!require("remotes", quietly = TRUE)) {
    install.packages("remotes")
}
## Install the tidytuesdayR package (from GitHub) if you don't have it
if (!require("tidytuesdayR", quietly = TRUE)) {
    remotes::install_github("dslc-io/tidytuesdayR")
}
```

```{r}
#download the data
tuesdata<- tidytuesdayR::tt_load("2022-01-18")
chocolate <- tuesdata$chocolate
```

```{r}
library("here")
library("tidyverse")

# tests if a directory named "data" exists locally
if (!dir.exists(here("data"))) {
    dir.create(here("data"))
}

# saves data only once (not each time you knit a R Markdown)
if (!file.exists(here("data", "chocolate.RDS"))) {
    url_csv <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv"
    chocolate <- readr::read_csv(url_csv)

    # save the file to RDS objects
    saveRDS(chocolate, file = here("data", "chocolate.RDS"))
}

chocolate<- readRDS(here("data", "chocolate.RDS"))
as_tibble(chocolate)
glimpse(chocolate)
```

<span style="font-size: 20px;">Part 1 1. Make a histogram of the rating scores to visualize the overall distribution of scores. Change the number of bins from default to 10, 15, 20, and 25. Pick on the one that you think looks the best. Explain what the difference is when you change the number of bins and explain why you picked the one you did.

```{}
```
